name: close-review-app
on:
  pull_request:
    types: [closed]
    branches:
      - '*'
      - '!master'

jobs:
  close-review-app:
    name: Close Review App
    runs-on: ubuntu-latest

    steps:
    - name: Set env
      run: |
        BRANCH=$(echo "${{ github.head_ref }}" | sed "s/\//\-/g") &&
        BRANCH=$(echo "$BRANCH" | sed "s/[0-9]*//g") &&
        BRANCH=$(echo "$BRANCH" | sed "s/\.//g") &&
        BRANCH=$(echo "$BRANCH" | sed "s/\-$//g") &&
        echo "BRANCH_PATH=deployed-$BRANCH" >> $GITHUB_ENV &&
        echo "BRANCH_NAME=$BRANCH" >> $GITHUB_ENV

    - name: Test new env
      run: |
        echo ${{ env.BRANCH_PATH }} &&
        echo ${{ env.BRANCH_NAME }}

    - name: Checkout repository
      uses: actions/checkout@master

    - name: Install Open VPN
      run: sudo apt install openvpn -y && sudo apt install expect

    - name: Connect VPN
      uses: golfzaptw/action-connect-ovpn@master
      id: connect_vpn
      with:
        PING_URL: '127.0.0.1'
        FILE_OVPN: '.github/vpn/config.ovpn'
        SECRET: ${{ secrets.SECRET_USERNAME_PASSWORD }}
      env:
        CA_CRT: ${{ secrets.CA_CRT}}
        USER_CRT: ${{ secrets.USER_CRT }}
        USER_KEY: ${{ secrets.USER_KEY }}
          
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.QA_ENDPOINT }}
        username: ${{ secrets.QA_USER }}
        password: ${{ secrets.QA_PASSWORD }}
        script: |
          branchPath=${{ env.BRANCH_PATH }} &&
          echo "$branchPath" &&
          cd ${{ secrets.QA_FOLDER }} &&
          cd .. &&
          if [ -d "$branchPath" ]; then rm -Rf $branchPath; fi &&
          echo "✅ Review App from branch \"${{ env.BRANCH_NAME }}\" was succesfully remove"

    - name: kill vpn
      if: always()
      run: sudo killall openvpn

    - name: Deactivated environment. ${{ env.BRANCH_PATH }}
      uses: bobheadxi/deployments@v0.4.3
      with:
        step: deactivate-env
        token: ${{ secrets.GITHUB_TOKEN }}
        env: review-app-${{ env.BRANCH_NAME }}
        desc: Deployment 'review-app-${{ env.BRANCH_NAME }}' was deactivated
