name: php-unit-test
on:
  push:
    branches-ignore: 
      master
  pull_request:
    branches: [ master, dev ]

jobs:
  php-unit-test:
    name: PHP Unit Testing
    runs-on: ubuntu-latest

    steps:
    - name: Setup PHP with PECL extension
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
    
    - uses: actions/checkout@v2

    - name: Install all dependencies
      run: composer install

    - name: UnitTest
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        APP_NAME: ${{ secrets.APP_NAME }}
        APP_ENV: ${{ secrets.APP_ENV }}
        APP_DEBUG: ${{ secrets.APP_DEBUG }}
        APP_KEY: ${{ secrets.APP_KEY }}
        APP_HOSTNAME: ${{ secrets.APP_HOSTNAME }}
        API_HOSTNAME: ${{ secrets.API_HOSTNAME }}
        APP_TIMEZONE: ${{ secrets.APP_TIMEZONE }}
        DB_CONNECTION: ${{ secrets.DB_CONNECTION }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
      run: composer test
        
    # - name: Coveralls
    #   env: 
    #     COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
    #     COVERALLS_ENTRY_POINT: "https://diloconflores.com"
      # run: composer test-coverage